Replace Remixer.remixerItemList with a WeakHashMap.
material-foundation/material-remixer-android pull request #71
Opened 2016-11-04 18:43 UTC by miguelandres

Currently there is no need for a flat data structure that contains all RemixerItems, instead, all operations look at either RemixerItems by key or by context. Particularly the operations that look at RemixerItems by contexts are really slow since they have to iterate by all remixes.

2016-11-04 18:44 UTC, miguelandres commented
This is so I don't add it to #50 that is large enough already, but they're closely related, if this goes in first I can make sure #50 accomodates for this and make the remixer class easier to look at.

2016-11-04 22:49 UTC, pingpongboss requested changes

2016-11-04 22:49 UTC, pingpongboss commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +   * <p>This method also removes old remixer items whose contexts have been reclaimed by the Garbage
Garbage Collector or garbage collector

2016-11-04 22:49 UTC, pingpongboss commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +      // reclaimed, that's why it's a WeakHashMap.
part of me still thinks you should keep this explicit removal. What happens in this case:
```
contextMap = {
  MainActivity : [ foo_var, bar_var ]
}
```

And `addItem()` causes `foo_var` to be removed. If you do not have explicit removal, won't `foo_var` stick around? It's not going to cause a memory leak or anything, but isn't it more clean to remove it explicitly?

2016-11-04 23:02 UTC, miguelandres commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +      // reclaimed, that's why it's a WeakHashMap.
sure :)

2016-11-04 23:05 UTC, miguelandres commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +      // reclaimed, that's why it's a WeakHashMap.
Well not really, the weakhashmap would have already removed it, since either the context has been reclaimed or it has been already removed in line 161, explicitly.

2016-11-05 03:41 UTC, miguelandres commented
Improved comments explaining why this still works.

2016-11-07 17:41 UTC, pingpongboss approved these changes

2016-11-07 17:41 UTC, pingpongboss commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +    getRemixerItemsForContext(remixerItem.getContext()).add(remixerItem);
This method depends on the precondition that `remixerItem` has a context. Can you add a check at the top of the method to assert that this is the case?

2016-11-07 17:41 UTC, pingpongboss commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +  private WeakHashMap<Object, List<RemixerItem>> contextMap;
regular map

2016-11-07 17:46 UTC, miguelandres commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +    getRemixerItemsForContext(remixerItem.getContext()).add(remixerItem);
Not really, though the null context doesn't make sense, the null key is valid as HashMap key.

2016-11-07 17:47 UTC, miguelandres commented on remixer_core/src/main/java/com/google/android/libraries/remixer/Remixer.java
> +  private WeakHashMap<Object, List<RemixerItem>> contextMap;
Done.

2016-11-07 17:50 UTC, merged