Add TravisCI support.
material-foundation/material-remixer-android pull request #74
Opened 2016-11-04 22:47 UTC by miguelandres

Also de-linting so it doesn't fail on its first run.

2016-11-04 22:57 UTC, pingpongboss requested changes

2016-11-04 22:57 UTC, pingpongboss commented on .travis.yml
> +    - extra-android-m2repository
can you verify that you need these 2 `extra-android-` components? See if travsici builds without them.

2016-11-04 22:57 UTC, pingpongboss commented on .travis.yml
> +  - ./gradlew build test
I suggest using `check` which includes `build` and `test` but also includes plugin outputs like jacoco (for code coverage).

2016-11-04 22:57 UTC, pingpongboss commented on README.md
> +[![Build Status](https://travis-ci.org/material-foundation/material-remixer-android.svg?branch=develop)](https://travis-ci.org/material-foundation/material-remixer-android) [![codecov](https://codeco
we have codecov on a separate line (in source) which helps readability

2016-11-05 02:57 UTC, miguelandres commented on .travis.yml
> +    - extra-android-m2repository
Android support is definitely necessary.

2016-11-05 14:55 UTC, miguelandres commented on README.md
> +[![Build Status](https://travis-ci.org/material-foundation/material-remixer-android.svg?branch=develop)](https://travis-ci.org/material-foundation/material-remixer-android) [![codecov](https://codeco
done

2016-11-05 14:55 UTC, miguelandres commented on .travis.yml
> +  - ./gradlew build test
done

2016-11-07 20:14 UTC, pingpongboss approved these changes

2016-11-10 16:28 UTC, miguelandres commented
Finally figured it out! Travis installs old tools by default, and you have to work around it by installing them twice.

https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943

I'll be squashing this PR, since the history is basically useless, a bunch of attempts to diagnose the issue.

2016-11-10 16:48 UTC, merged

2016-11-10 17:56 UTC, pingpongboss reviewed
Hmm think I should do this for MM?

2016-11-10 23:00 UTC, miguelandres commented
Probably...it may be that your target api is 23 and it hasn't affected you
but it would if you move to 24/25

Den tors 10 nov. 2016 12:56Mark Wei <notifications@github.com> skrev:

> *@pingpongboss* commented on this pull request.
>
> Hmm think I should do this for MM?
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/material-foundation/material-remixer-android/pull/74#pullrequestreview-8063069>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJxqD5TIcIIuBHbAqnXjCJrTHIK_UVeks5q81rogaJpZM4KqEBG>
> .
>